[package]
cairo-version = "2.12.2"
name = "witchcraft"
version = "1.7.2"
edition = "2024_07"

[scripts]
dev = "./dev.sh"

[cairo]
sierra-replace-ids = true

[dependencies]
starknet = "2.12.2"
dojo = "=1.7.2"

[profile.sepolia]
# Sepolia profile configuration
# Use with: sozo -P sepolia build/migrate

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dev-dependencies]
cairo_test = "2.12.2"
dojo_cairo_test = "=1.7.2"
# dojo_snf_test = "=1.7.2"
